version: 2
updates:
  - package-ecosystem: "pub" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      separator: /
    target-branch: "main"
