name: synchronous_stream
description: Synchronous notifier that implements `StreamController` variant with O(1) broadcast unsubscription (swap-remove) and compact tagged queues (pre-listen/pause) with lazy stack-trace capture and allocation-lean hot paths
version: 1.0.0
homepage: https://github.com/arxdeus/synchronous_stream
repository: https://github.com/arxdeus/synchronous_stream
issue_tracker: https://github.com/arxdeus/synchronous_stream/issues

topics:
  - architecture
  - stream
  - reactivity

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.2.0

dependencies:
  meta: ^1.14.0

dev_dependencies:
  fake_async: ^1.0.0
  stream_transform: ^2.0.0
  test: ^1.23.0


