name: Codecheck

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - 'main'
  push:
    branches:
      - "**"

permissions:
  contents: read
  actions: read
  checks: write

env:
  FLUTTER_TEST_REPORT: ${{github.workspace}}/dart-test-report.json

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      file-changed: ${{ steps.matrix.outputs.file-changed }}
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: Get Dart SDK version constraints and packages
        id: matrix
        uses: arxdeus/github_workflows/actions/dart_parse_versions@main
  code_check:
    name: "Codecheck - ${{ strategy.job-index }}"
    runs-on: ubuntu-latest
    needs: setup
    if: ${{ needs.setup.outputs.file-changed == 'true' || github.event_name == 'pull_request' }}
    strategy:
      matrix: ${{ fromJson(needs.setup.outputs.matrix) }}
    timeout-minutes: 10
    steps:
      - name: "Codecheck"
        uses: arxdeus/github_workflows/actions/dart_codecheck@main
        with:
          dart-version: ${{ matrix.dart-version }}
