name: Release to pub.dev
on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    name: "Publish"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
    - name: "Checkout repository"
      uses: actions/checkout@v4
      with:
        fetch-tags: true
        fetch-depth: 0

    - name: "Setup Dart"
      uses: dart-lang/setup-dart@v1
      with:
        sdk: stable

    - name: "Run Publish"
      shell: bash
      run: dart pub publish --force
